
#include <common.h>
#include <asm/arch/pxa-regs.h>
#include "adsbitsyxb.h"

#ifdef CONFIG_PCMCIA_SLOT_A
void pcmcia_power_on(void)
{
	if (!(ADSBITSYXB_PCMCIA_SR & ADSBITSYXB_SR_CARDA_VS1)) /* 3.3V */ {
		ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDA_5V;
		ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDA_3V;
	}
	else /* 5.0V */ {
		ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDA_3V;
		ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDA_5V;
	}

	ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDA_RES;

	udelay(300000);

	ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDA_RES;

	udelay(200000);
}

void pcmcia_power_off(void)
{
	ADSBITSYXB_PCMCIA_CR &= ~(ADSBITSYXB_CR_CARDA_5V | ADSBITSYXB_CR_CARDA_3V);
}
#else
void pcmcia_power_on(void)
{
	if (!(ADSBITSYXB_PCMCIA_SR & ADSBITSYXB_SR_CARDB_VS1)) /* 3.3V */ {
		ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDB_5V;
		ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDB_3V;
	}
	else /* 5.0V */ {
		ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDB_3V;
		ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDB_5V;
	}

	ADSBITSYXB_PCMCIA_CR |= ADSBITSYXB_CR_CARDB_RES;

	udelay(300000);

	ADSBITSYXB_PCMCIA_CR &= ~ADSBITSYXB_CR_CARDB_RES;

	udelay(200000);
}

void pcmcia_power_off(void)
{
	ADSBITSYXB_PCMCIA_CR &= ~(ADSBITSYXB_CR_CARDB_5V | ADSBITSYXB_CR_CARDB_3V);
}
#endif
